name: 'Validate PR links to Azure Boards'

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - master
      - release/*

jobs:
  check-ab-link:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 'Check for AB# in PR body'
        uses: danhellem/github-actions-pr-is-linked-to-work-item@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
